### ISSUE TITLE
Display the list of next forgers in delegates monitoring

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#2624]
### Description
As a user; I'd like to see the list of next forgers according to [designs](https://projects.invisionapp.com/d/main/#/console/18539694/389182920/preview). 

### Acceptance criteria
- the list update every 10 sec.
- Total forged value should have thousand separators.

**Comment by MichalTuleja** [comment]
The data can be retrieved from Lisk Service.

- Next forgers: Call the `/api/v1/delegates/next_forgers` endpoint,
- Last forger: 
  - Request `/api/v1/blocks/last?limit=1` (`generatorUsername `)
  - To get real-time updates subscribe to the `update.block` event 
- Total forged:
  - Call the `/api/v1/network/status`
  - Subtract the current `supply` from the `initial supply = 10000000000000000`
  - The value increases with a new block
  - This is an approximate value - some small amounts were burned in the past due to network errors/software bugs. To have an exact values we would need to sum up all accounts which is possible on the backend only.
