### ISSUE TITLE
Monitoring: Block: Filtering should not be available

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-desktop#2639]
### Steps to reproduce

1. Open Blocks monitor
1. Click on specific block
1. Click Filter

### Actual result

Opens filter popup with no options

### Expected result

No Filter button for Blocks

### Version

1.23.0-beta

### Screenshot (if appropriate)

![image](https://user-images.githubusercontent.com/6704159/68682609-b1243f80-0565-11ea-89ba-58c32eb1a75f.png)

**Comment by slaweet** [comment]
Fixing this should be as simple as changing

https://github.com/LiskHQ/lisk-desktop/blob/e4dcc3dbd73852d581d446fdf85e7611418ab099/src/components/shared/filterDropdownButton/index.js#L138
to
```js
    return fields.length === 0 ? null : (
```

This bug happened because when the transactions table was added to the block details page in https://github.com/LiskHQ/lisk-desktop/commit/c6d4787d9e824a14ee1e48c67f16d3c649a3da9d#diff-a2a18b6ed7f14d847fded4da03af69feR210-R215 the `TransactionsTable` didn't have the filter button, so everything was ok back then.
