### ISSUE TITLE
Live data for monitor

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-desktop#2662]
1.23.0-rc1

Regarding the new monitor feature:

Transactions and blocks should be updated live, in real-time. Currently neither blocks NOR the confirmations update. You always have to switch to another tab and then back to "monitor" to get the latest status.

Live data for Delegates is almost good but I would like to know if it's possible to get update every second, in real-time like exchanges offer their UX through a websocket-system?

**Comment by slaweet** [comment]
Transactions and blocks are planned to be handled as described in:
https://github.com/LiskHQ/lisk-desktop/issues/2513
https://github.com/LiskHQ/lisk-desktop/issues/2510

It's not exactly what you asked here, but it gives some rationale for why.

Delegates monitor is connected to websocket and should be updated as soon as there is a new block. But I'm aware of some bugs being fixed in https://github.com/LiskHQ/lisk-desktop/pull/2641
- it doesn't work without login; 
- it doesn't update forging time on missed blocks.

Thank you for the feedback, @punkr0ck, and We'll be happy to read 🙂from you if you have some more thoughts on this.

**Comment by reyraa** [comment]
I close this one in favor of #2513 and #2510.
