### ISSUE TITLE
Monitoring: Load more button is not shown after several fetchings

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-desktop#2669]
### Expected behavior
Load more is always there
### Actual behavior
It is not shown after several uncertain number of loadings
### Steps to reproduce
1. Go to monitoring
1. Blocks
1. Click Load more until you cant see the button
### Which version(s) does this affect? (Environment, OS, etc...)
1.23.0

**Comment by slaweet** [comment]
I think it happens if a new block was forged.

Because `limit=30&offset=30`  after a new block is forged returns one block that is already on the page, so there are only 59 blocks, it thinks there are no more blocks. Because I didn’t write the logic properly but used a quick hacky way:  https://github.com/LiskHQ/lisk-desktop/blob/development/src/components/screens/monitor/blocks/blocks.js#L117
