### ISSUE TITLE
add tooltip in network statistics (Graph view)

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#2836]
Investigate and implement adding tooltip in network statistics (Graph view)

**Comment by slaweet** [comment]
I have built a PoC that adds a tooltip to the delegates page "Missed block" in "Delegates Forging Status". The proposed solution allows labels of DoughtnutChart to be custom React code and renders those in a custom `Legend` react component instead of the native chart.js labels.

Live demo: https://ci.lisk.io/test/lisk-desktop/2836-chart-tooltip-poc/#/monitor/delegates

Source code: https://github.com/LiskHQ/lisk-desktop/compare/2836-chart-tooltip-poc

**Comment by yasharAyari** [comment]
I like the soulution that you found. I will try your way.
