### ISSUE TITLE
Support full passphrase in newest Trezor firmwares (1.9.0 and 2.3.0)

### ISSUE THREAD

**Issue by tsusanka** [LiskHQ/lisk-desktop#2864]
We have done some modifications regarding how passphrase is communicated between Trezor and the host.

Please upgrade the [trezor-connect](https://www.npmjs.com/package/trezor-connect) dependency of your application to latest (8.1.1 atm), otherwise your users won't be able to enter passphrase on the device (on Trezor T).

Thanks!

Related:  #2214

**Comment by punkr0ck** [comment]
This is urgent as you aren't able to access your LSK.

**Comment by hirishh** [comment]
Hello @tsusanka 

lisk-desktop (and also liskish-wallet) use mainly `trezor.js` in order to integrate it with the electron app. Trezor-connect is used only in the web-development phase. Is the `trezor.js` updated also? Is it possible to integrate `trezor-connect` with electron?

**Comment by reyraa** [comment]
Thanks for the heads-up @tsusanka tsusanka. This is planned for the current week. I'll get in touch if I needed more info. thank you.

**Comment by szymonlesisz** [comment]
Hi @hirishh
`trezor.js` was deprecated about a year ago and receives only important fixes (like this one)
`trezor-connect` works in web, nodejs, electron and even react-native (Android only)

I was trying to add `trezor-connect` to this project but if found that you don't work with `passphrase` at all. The only handled requests from the device is CONNECT/DISCONNECT/PIN (on T1).

Summary:
You are not affected by this change.
Not because of outdated `trezor.js` but because you don't handle trezor passphrase requests at all, so it wasn't event with previous firmware versions.

I would strongly recommend to use `trezor-connect`. Since i wasn't able to run it here i will prepare some examples in [connect branch](https://github.com/trezor/connect/tree/feature/examples/examples/electron) to show you possible ways to implement it

**Comment by szymonlesisz** [comment]
I believe this is your case: trezor-connect in main electron process and communication thru ipc:

https://github.com/trezor/connect/tree/feature/examples/examples/electron/main-process

**Comment by hirishh** [comment]
Hello @szymonlesisz,

Thank you for the heads up. It's true lisk desktop is not using passphrase fuctionalities, but liskish wallet does ( https://github.com/hirishh/liskish-wallet/blob/2.0.0/app/src/hw/trezor.js#L108 )

Thank you for the example with electron. I will try to integrate it and get rid of trezor.js.

Thanks!

**Comment by hirishh** [comment]
Hello @reyraa,
Actually, I think lisk-desktop is broken. Apparently inserting passphrase is mandatory (the device expect that). If you do not want to implement this functionality, at least you need to listen on  "passphrase" event and set an empty string directly without interacting with the user.

hirish

**Comment by punkr0ck** [comment]
@reyraa it has to be implemented. if you don't people who use passphrases can't use lisk dekstop anymore. i posted about this in mid 2019: https://github.com/LiskHQ/lisk-desktop/issues/2214

now it is mandatory.

**Comment by reyraa** [comment]
The passphrase issue is resolved and will be available via v1.27.2. But migrating to `trezor-connect` will come in a dedicated: version v2.1.0.

**Comment by ManuGowda** [comment]
Adapt hardware wallet integration for Lisk Core v4  will ensure the firmware is updated https://github.com/LiskHQ/lisk-desktop/issues/4041
