### ISSUE TITLE
Security compromised/Private Keys Stolen - lisk-hub-linux-x86_64-1.9.0-rc.1.AppImage

### ISSUE THREAD

**Issue by JohnFaraday42** [LiskHQ/lisk-desktop#3277]
Unfortunately today I found out, someone else had accessed my Lisk address and drained all funds.
I was using a bootable USB with solely Ubuntu 16.04 and Lisk-hub-linux-x86_64-1.9.0-rc.1.AppImage

On 28-Dec-2020 I booted the USB for the first time since years. I opened Lisk-hub-linux-x86_64-1.9.0-rc.1.AppImage to check my funds. Everything was OK. 

Today I did the same thing. This time, I was extremely surprised to see my funds were withdrawn from my address 2872407335501508079L to an unknown recipient 15071341940496556204L.

As you can see on the Lisk Blockchain Explorer, this recipient has received many incoming transactions within a short time frame, indicating automated theft from multiple wallets. This makes me think it must me a targeted attack towards Lisk users, and perhaps exploiting some vulnerability within Lisk Hub.

Although I am not a developer, and I am unable to analyze the Lisk-hub package my self to see if there is indeed malware included, I hope this is taken seriously. It seems highly unlikely that the Attack vector was anything else, as I was using this Ubuntu USB stick solely for the purpose of Cold storage, and was connected to a secure LAN.

If there is any additional information I can provide, please let me know.

**Update**
I know strongly suspect this has to do with the security of Uninitialized wallets, as all the transactions to the thief came from wallets that were not initialized (including mine). (https://www.lisk.support/lisk-support/initialize-your-address/)
I have also checked my bootable USB for malware, and other security issues, and did not find any so far.

**Comment by karmacoma** [comment]
Hello @JohnFaraday42,

I am sorry hear your bad news. The funds were withdrawn from your account because it was not initialised. There is unfortunately nothing which can be done to retrieve the funds.

You appear to be using an old version of Lisk Hub, now called Lisk Desktop. In later versions, we explicitly warn users to initialise their account by sending at least one outgoing transaction. This is done within the application as a single transaction to oneself with a small fee.

We also offer the feature of a second passphrase for additional protection of your account, which I believe is available in the version of Lisk Hub you are using.

Our advice to anyone wanting to avoid such a situation is to:

- Always initialise your new account (send at least one outgoing transaction, of any type)
- Always use the latest version Lisk Desktop (automatic updates are provided)
- Register a second passphrase for additional protection

Please note, when Lisk Core version 3 is released onto the mainnet, the account initialisation step will no longer be required. Users will also have the ability to register a multi-signature group for additional account security, similar to the second passphrase option currently offered.

I am therefore tentatively closing this issue. Thank you for the information you provided.
