### ISSUE TITLE
Important metadata for the team, please do not edit:

### ISSUE THREAD

**Issue by ksepehri-troy** [LiskHQ/lisk-desktop#3496]
{"error":{"jse_shortmsg":"Transaction was rejected with
errors","jse_info":{},"message":"Transaction was rejected with
errors","name":"APIError","errno":409,"errors":[{"message":"Invalid
sender publicKey","name":"TransactionError","id":"9718071869611445025","dataPath":".senderPublicKey","actual":"63739ca66260aa28610220724685b17f74fd43e21ffe5108a110dd0d53a24e44","expected":"4c5fc4f73ca2245466131f451ab853f392fc7a28d3063b55e23cd05eff6fce4b"}]},"transaction":{"amount":"60010000000","recipientId":"6541858718912961316L","senderPublicKey":"63739ca66260aa28610220724685b17f74fd43e21ffe5108a110dd0d53a24e44","timestamp":153360620,"type":0,"fee":"10000000","asset":{"data":"hiloox"},"signature":"7ddd5a6d6ee808ad49af7b6d0500dd42759ca78628ec7fb4827ee35c1c854d521b3413ef6452f8db72359172d8bd3cf25b611edc34c2c651fa5a658d5993580a","id":"9718071869611445025"}}

**Comment by karmacoma** [comment]
Hello @ksepehri-troy,

The error message you have received means your account was subject to an address collision attack. Unfortunately there is nothing we can do to fix this from the perspective of Lisk Desktop.

Please read the following blog post for more information on how this issue is being handled:  https://lisk.io/blog/announcement/lisk-account-initialization

Thanks.
