### ISSUE TITLE
Prompt users to update the app if they see an error on an outdated version

### ISSUE THREAD

**Issue by UsamaHameed** [LiskHQ/lisk-desktop#3518]
### Description

It would be helpful to show the users that there is a new version of the app available in case they encounter an error on an old version and that error is possibly fixed in the new version.

### Motivation

Enable users to reliably use the app

### Acceptance Criteria

Check for updates in error modals/screens and show an option to update

**Comment by ManuGowda** [comment]
If there is a new version of the app available, the auto updater already informs users to update the app? however, I see the motivation behind the improvement, for the moment all the bug fixes are done through patch releases and they are informed by auto updater, we do not need to add any more intelligence than that for the moment.

**Comment by ManuGowda** [comment]
This issue was also opened in favour of improving connectivity issue with service when it was migrated from cloud, and the API was unstable due to which there were bugs, now that we have service which is stable, we do not need to change anything. 

@reyraa when we implement notification objective along with service, we should consider some of these requirements to improve the prompting of users based on requirements.
