### ISSUE TITLE
Forging details graph shows incorrect data

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#3714]
### Actual behavior

![image](https://user-images.githubusercontent.com/25085095/126904003-c1ffd9f1-6b23-465e-b074-7e943c8df0f7.png)
After 103 delegates had a chance to forge in a current round and the round continues (because of missed blocks), **forging** part of the graph shows number of forged blocks, not the real number of delegates that didn't miss their blocks. Contrary to what the screen shows, the real number of forging delegates was less than 90.

### Which version(s) does this affect? (Environment, OS, etc...)

2.0.0-rc.3

**Comment by ManuGowda** [comment]
Thank you @przemerr for reporting the issue, after discussing I got some more context. Here is the extended information regarding the bug.
Let's say there are 103 delegates selected for forging in the round. When a round starts few delegates could be active and few could be inactive. For example at the end of round if there are only 92 delegates were active and 11 missed the slot to forge, then in the donut chart we should show 92 forged, 11 missed. Even though the round is extended (Minutes passed), the same delegate who is active in the round will forge the missed slot, so overall only those 92 active delegates forged and not 103 delegates forged.

Currently, even though 11 delegates missed their slots to forge, at the end of round (extended) we show 103 forged, which is incorrect.

**Comment by reyraa** [comment]
@ManuGowda @przemerr 

We have two charts. 
1. Slot status: This chart shows the distribution of the forged, pending (awaiting) and missed slots. The more missed slots, the bigger the total number. The aim is to depict the ratio of missed blocks in comparison to awaiting + forged. The bigger the chunk of missed blocked, the worse the performance of the nodes. So from this stand point, the first chart accomplishes its purpose.
2. Round status: This chart demonstrates the progress of the round. Regardless of missed blocks, every round is complete when 103 blocks are forged. This chart shows how many blocks are forged and how many remaining in the current round. This chart doesn't take the missed blocks into account because they are already depicted in the first chart. There's no need for duplication. I believe the round status chart is useful and accomplishes its purpose.

Therefore I close this ticket.
thank you for your feedback guys.
