### ISSUE TITLE
There is a pattern of multi-sign that cannot be signed with the mandatory key.

### ISSUE THREAD

**Issue by lisknonanika** [LiskHQ/lisk-desktop#3727]
### Expected behavior
Even if the number of signatures is met with the optional key first, it should be possible to sign with the mandatory key.

### Actual behavior
If an account has at least one mandatory key and the number of optional keys is greater than the number of signatures, if the number of signatures is met with the optional keys first, the account cannot be signed with the mandatory  keys.

### Steps to reproduce
For a multi-signature account like the following:
```
"keys":{
    "numberOfSignatures":2,
    "mandatoryKeys":["aaa…"],
    "optionalKeys":["bbb…","ccc…"],
    "members":[…]
}
```
Sign with two optional keys.
(Do not sign with the mandatory key.)

Probably because this does not take into account the number of signatures for the mandatory key.
https://github.com/LiskHQ/lisk-desktop/blob/development/src/components/screens/signMultiSignTransaction/helpers.js#L36

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Desktop 2.0.0

**Comment by sridharmeganathan** [comment]
Thank you. We will validate this issue and fix it in the next release

**Comment by reyraa** [comment]
I think there's a misconception in what the number of signatures is.

When an account is configured to have numberOfSignatures = 2, transactions should be signed by exactly 2 members, not more and not less.
If you have a mandatory member, s/he should sign the transaction. otherwise the transaction doesn't meet signature criteria. In your example, you need one signature from your mandatory member, and exactly one signature from one of your optional members. not both, not none, exactly one.

**Comment by lisknonanika** [comment]
I have that understanding. I know it is not a priority, but I feel it should be checked to prevent this situation from happening.
e.g. "Cannot sign any more with optional key."
