### ISSUE TITLE
Transaction failed for vote and send LSK

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#3783]
### Expected behavior
As a user i'm  allowed to send more than one transaction when there is sufficient balance in my account

### Actual behavior
As a user im unable to send more than one transaction. This is applicable for vote and send transactions
![image](https://user-images.githubusercontent.com/51332105/133208222-dba69881-f824-4afe-8002-a0cf191cbe29.png)

### Steps to reproduce

1. Sign in to the wallet page --> send LSK to other account 
2. Wait for the transaction confirmation.
3. After the previous transaction got confirmed, now send the new transaction

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.1

**Comment by ManuGowda** [comment]
**Investigation Report**

Current implementation:
Lisk Desktop allows users to create transaction and the after the successful creation and inclusion of transaction in the block, the store is updated with `nonce`.

Flow: Transaction Create (Desktop) -> Broadcast (Desktop) -> Send to core (Service) -> Included in block (Lisk Core) (10sec window) -> New Block Event (Lisk Core) -> Query accounts for latest state (Desktop to Service) -> Update store with latest account state `nonce` (Desktop)

During the above described flow, when a new block events sends information about inclusion of transaction, the service returns **outdated account information due to caching**.

Since service returns the outdated account info due to caching, we store the invalid account info. And the account store will never be up to date and a logged in users will never be able to make successful transaction from here onwards.

The only work around of users is to logout and log in, as the account store will be updated (10 second caching expired by service).

**Comment by ManuGowda** [comment]
The Lisk Desktop was not updated to fix any issue as the Lisk Service caching at proxy level is been addressed. From Lisk Desktop, we have improved to show better error message and for reporting via email we have added few more details so that it is easier to understand the reports and take action in the future.
