### ISSUE TITLE
Delegate punishment warning shown only when signed in

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#3976]
### Expected behavior

Punishment warning should be visible regardless of being signed in or not.

### Actual behavior

Punishment warning is not visible on a punished delegate page when not signed in.

### Steps to reproduce

Open the wallet, don't sign in, go to delegate section, select any `punished` delegate from the `sanctioned` tab.

### Which version(s) does this affect? (Environment, OS, etc...)
 Windows, 2.2.0-beta.0

**Comment by reyraa** [comment]
The delegate profile page informs the punishment status in 3 places:
1. Under the details column.
2. Under the performance section which has a big title, descriptions and a warning illustration.
3. As a warning on top of the page.

The warning message is intended to discourage users from voting to sanctioned delegates. If you are not signed in, it means you are not voting, hence it seems unnecessary to show a warning message, since there's no  consequence to the user's action of opening delegate profile. I believe the fist two places clarify the status of the delegate clearly.

Now if you sign in by intention of voting, you'll get an additional warning message. I'd argue that an additional outstanding component in the page that you just visited, attracts more attention and might yield to an even better outcome.

If you still think we should display the warning message even when the user is not signed in, please explain your reasons.

Thank you

**Comment by przemerr** [comment]
I found it a bit inconsistent at first, but it's true, a user that wants to vote for a punished delegate can't miss the warning since he has to sign in and there's also a warning in the voting modal 
![image](https://user-images.githubusercontent.com/25085095/143853200-12d6b417-9797-4239-9a6b-cd86760ea9f5.png)
 In that case issue can be closed 👍  Thank for sharing your point of view.

**Comment by ManuGowda** [comment]
Thank you @przemerr 🙏🏼
