### ISSUE TITLE
Unable to sign transactions with second passphrase/multisig accounts

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-desktop#4076]
### Expected behavior
User should be able to sign transactions
### Actual behavior
While trying to sign a transaction using the second pass feature after clicking `Sign` a faulty popup appears which makes impossible to send the transaction. 

![image](https://user-images.githubusercontent.com/25085095/149619785-65e864b4-3243-48c7-821e-e080d41ac339.png)

Also if you try to send a multisig transaction without the second pass feature, it seems to be impossible to sign with the second key, you get a `Successful signing` pop up with no ability to send. 

![image](https://user-images.githubusercontent.com/25085095/149619917-cd1e2e3c-d2fd-46b4-9173-0c2c2d46bf54.png)
 
### Steps to reproduce
Try sending a transaction with a "second passphrase" account using the `Sing with the second key right away` and try the regular signing with json files also.
### Which version(s) does this affect? (Environment, OS, etc...)
Windows, Lisk Desktop 2.2.0-beta.1

**Comment by hirishh** [comment]
Same problem on the Linux version. It totally freezes the software just after clicking "Sign" when "sign with the second key right away" path

**Comment by Lemii** [comment]
Confirmed here on M1 MacBook using Monterey.

**Comment by reyraa** [comment]
This issue seems to have been fixed by  #4070 and #4071. I managed to create txs on testnet using second passphrase input and the Sign Multisignature Transaction tool.
Here are the tx IDs:

Account No 1:
e00f6257b527eeec365d1f8d9d6f4d76021c73ac811c66be6389d00c03de68cc (Using multisig tool)
c0912158a05454a11be94bf33471dc3e925f5804a2e29e0273f0223801dc2274 (Using second pass)

Account No2:
6ec5f737d42654808ad82925c4a20e692df3a420258b1a2857a00ff66b74f4e8  (Using multisig tool)
44ee89039c89ec47bbf2d47749cd97c27c5479702fba3dbc03f6d9926e1ebcc0 (Using second pass)
