### ISSUE TITLE
Visual issues observed while testing Lisk Desktop v3.0.0-alpha.3 on Linux

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#4971]
### Expected behavior

- Icons are visual aids. They should be easily recognizable. 

### Actual behavior

- The validator status icons are in general small, but this one is too small.
![Issues - Validator status icon](https://user-images.githubusercontent.com/666685/235970710-ee214715-a7b9-45ab-a065-efe63578998f.png)

### Which version(s) does this affect? (Environment, OS, etc...)
v3.0.0-alpha.3
Ubuntu 22.04

**Comment by ManuGowda** [comment]
### These issues are already resolved

- The fee is displayed as undefined (Two screenshots). 
![Issues - Undefied fee - 1](https://user-images.githubusercontent.com/666685/235970696-5b672444-3a08-4acd-919b-02b32b353dd9.png)
![Issues - Undefined fee - 2](https://user-images.githubusercontent.com/666685/235970703-ef62749d-5090-4536-a7e3-78439a0f2ddf.png)
- The reward details link is not clickable.
![Issues - Validator rewards details](https://user-images.githubusercontent.com/666685/235970707-a0c58b27-a704-49ee-8ac7-8c4ff0d625c9.png)

- The tooltip of the middle chart is a barely visible empty bubble of 10px x 10px.
![Issues - Transactions overview](https://user-images.githubusercontent.com/666685/235966063-ba08d3ac-1f2a-4426-bb89-064200ca886d.png)
- Although the other APIs respond, this API seems to throw. I don't have this issue on Mac.
![Issues - 404](https://user-images.githubusercontent.com/666685/235970690-957ec245-879c-4fc6-9a8c-5eede2dd7154.png)

- The total supply overflows from the box
![Issues - Text overflow](https://user-images.githubusercontent.com/666685/235966058-8d2e324f-b4da-4583-aae5-06f2f492bba1.png)

- Charts show a canvas with no data instead of a properly designed illustration.
- There are missing colors in the guides.

**Comment by ManuGowda** [comment]
The above issues are outdated, maybe we should test on beta.0 release on linux to know the recent issues.
