### ISSUE TITLE
All Ledger hardware wallet accounts created before hardfork can't be accessed

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-desktop#5530]
Lisk Desktop v3.0.0 is unable to import accounts from Ledger hardware wallets that were created before yesterdays hardfork, so basically all accounts. No one is able to access their LSK at the moment with the Lisk Ledger app v3.0.0 + Lisk Desktop v3.0.0. It has something to do with the derivation path, we guess. **Please take this very serious with highest priority and get it fixed asap. Thank you!**

**Comment by ManuGowda** [comment]
Currently the Lisk App on Ledger Live is Testnet version and not the official production version.

However, the issue might be available on Production app as well (which is under review), currently we are investigating this issue internal, we will give update as soon as possible.

**Comment by ManuGowda** [comment]
This issue was resolved with firmware update, hence closing.

Please do not use the production app, wait for Ledger Live to release the production app.

Meanwhile to test this bug, you can download https://hub.zondax.ch/lisk `3.0.1` version for testing. Any transactions done using this version is on your own risk, please use Testnet network for doing testing.
