### ISSUE TITLE
Batch sending LSK to wallets

### ISSUE THREAD

**Issue by ghost** [LiskHQ/lisk-desktop#978]
It is really anoying sending 10 transactions with a 2nd passphrase. It would save up a lot of time if you could just 'add to batch' and send all 10 tx with only entering your 2nd passphrase once.

**Comment by Joo5t** [comment]
enhancement?

**Comment by slaweet** [comment]
Technically easier to implement would be to add a checkbox `Remember my 2nd passphrase for next 10 minutes` to the 2nd passphrase step, unchecked by default.
@Joo5t What would you think about that?

**Comment by Joo5t** [comment]
Sounds like an easy and great improvement to me 👍

**Comment by reyraa** [comment]
Since this ticket has been sitting in out backlog for long I'd like to explain why we didn't take any action on it.

We have two vivid situation:
1. User would like to send various amounts to different recipients. We can argue as a user you would face the following 
   A. The Send form is already complex and if we add possibility to indicate more recipients and with each one a new amount, most users will have a hard time getting acquainted with the form. 
   B. Reviewing the form and ensuring the list if correct is increasingly harder.
   C. Considering each transaction requires an individual API call and by nature is likely to fail independent from others, makes the success/failure page extremely confusing.

2. User would like to send a single amount to several recipients. This scenario has all above issues except the form is a little bit less complex.

The solution suggested by @slaweet seems to solve the issue with another approach. Since soon we'll replace 2nd passphrase in its current form with the new multisignature feature, I'd suggest we touch this topic when the said feature is released to mainnet.
